### ISSUE TITLE
Hierarchical argument parsing

### ISSUE THREAD

**Issue by pieterhijma** [HarshitaSaraswat/Commandline_Preference_Management#3]
Currently, the arguments are not hierarchical which makes the usage a more unclear than necessary. For example, currently, `-v` is a possible parameter for the `read` command, but giving it a value does not make sense. I propose to set up the arguments in a hierarchical way.

This issue is related to #4 and [this gist](https://gist.github.com/pieterhijma/6224393fa7dd0d28ca5b5da26da3b63e) is a mockup for both things.

**Comment by HarshitaSaraswat** [comment]
I have completely removes -n --name for specifying the name of parameter. Instead, not the parameter_name is denotes as group_path:parameter_name (i.e. separated with a single ':'). Also added another command called 'list' that only operates on parameter groups.

**Comment by pieterhijma** [comment]
Cool, thanks, closing.
