### ISSUE TITLE
Argument completion

### ISSUE THREAD

**Issue by pieterhijma** [HarshitaSaraswat/Commandline_Preference_Management#4]
This is related to #3: If you have hierarchical command line parsing, it is easier to automatically generate completion files. I have a mockup for both things in [this gist](https://gist.github.com/pieterhijma/6224393fa7dd0d28ca5b5da26da3b63e).

**Comment by HarshitaSaraswat** [comment]
I have added completion for group path as well as parameter which are separated with ':' (eg-> BaseApp/Preferences/PythonConsole:PythonBlockCursor)
Along with this I have also added hierarchy in commands with sub-parser.

**Comment by pieterhijma** [comment]
Cool, closing.
